/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/admin/auth/register": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
            firstName: string;
            lastName: string;
            /** @enum {string} */
            role: "admin" | "user";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              /** @enum {string} */
              role: "user" | "admin";
              /** Format: email */
              email: string;
              firstName: string;
              lastName: string;
            };
          };
        };
      };
    };
  };
  "/api/admin/invite/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "user";
            /** @enum {string} */
            sender: "sendGrid" | "resend";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/admin/invite/resend": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            /** @enum {string} */
            sender: "sendGrid" | "resend";
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/admin/post/": {
    get: {
      parameters: {
        query?: {
          limit?: number;
          offset?: number;
          page?: number;
          searchQuery?: string;
          sortBy?: "title" | "createdAt" | "commentsCount";
          sortDirection?: "asc" | "desc";
          minCommentsCount?: number;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              meta: {
                total: number;
                limit: number;
                offset: number;
                page: number;
                totalPages: number;
              };
              posts: {
                  id: string;
                  title: string;
                  description: string;
                  authorId: string;
                  author: {
                    id: string;
                    /** Format: email */
                    email: string;
                    firstName: string;
                    lastName: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  };
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: date-time */
                  createdAt: string;
                  commentsCount?: number;
                  tags: {
                      /** Format: uuid */
                      id: string;
                      name: string;
                    }[];
                }[];
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description: string;
            /** @default [] */
            tags?: {
                /** Format: uuid */
                id?: string;
                name: string;
              }[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              title: string;
              description: string;
              authorId: string;
              author: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              comments?: {
                  id: string;
                  postId: string;
                  authorId: string;
                  author: {
                    id: string;
                    /** Format: email */
                    email: string;
                    firstName: string;
                    lastName: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  };
                  text: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
              tags: {
                  /** Format: uuid */
                  id: string;
                  name: string;
                }[];
            };
          };
        };
      };
    };
  };
  "/api/admin/post/{postId}/": {
    get: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              title: string;
              description: string;
              authorId: string;
              author: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              comments?: {
                  id: string;
                  postId: string;
                  authorId: string;
                  author: {
                    id: string;
                    /** Format: email */
                    email: string;
                    firstName: string;
                    lastName: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  };
                  text: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
              tags: {
                  /** Format: uuid */
                  id: string;
                  name: string;
                }[];
            };
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            title?: string;
            description?: string;
            /** @default [] */
            tags?: {
                /** Format: uuid */
                id?: string;
                name: string;
              }[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              title: string;
              description: string;
              authorId: string;
              author: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              comments?: {
                  id: string;
                  postId: string;
                  authorId: string;
                  author: {
                    id: string;
                    /** Format: email */
                    email: string;
                    firstName: string;
                    lastName: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  };
                  text: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
              tags: {
                  /** Format: uuid */
                  id: string;
                  name: string;
                }[];
            };
          };
        };
      };
    };
  };
  "/api/admin/post/{postId}/comment/": {
    get: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              comments: {
                  id: string;
                  postId: string;
                  authorId: string;
                  author: {
                    id: string;
                    /** Format: email */
                    email: string;
                    firstName: string;
                    lastName: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  };
                  text: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
            };
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            text: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              postId: string;
              authorId: string;
              author: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
              text: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
  "/api/admin/post/{postId}/comment/{commentId}/": {
    patch: {
      parameters: {
        path: {
          postId: string;
          commentId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            text: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              postId: string;
              authorId: string;
              author: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
              text: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
  "/api/admin/tags/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              name: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
  "/api/admin/tags/{tagId}/": {
    post: {
      parameters: {
        path: {
          tagId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              name: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          tagId: string;
        };
      };
      responses: {
        /** @description Default Response */
        204: {
          content: {
            "application/json": "null" | null;
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          tagId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              name: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
  "/api/admin/users/": {
    get: {
      parameters: {
        query?: {
          searchQuery?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              users: ({
                  /** Format: email */
                  email: string;
                  firstName?: string;
                  lastName?: string;
                  emailVerified?: boolean;
                  isEnabled?: boolean;
                  mfaEnabled?: boolean;
                  /** @enum {string} */
                  status?: "FORCE_CHANGE_PASSWORD" | "CONFIRMED" | "PENDING_CONFIRMATION";
                })[];
              paginationToken?: string;
            };
          };
        };
      };
    };
  };
  "/api/admin/users/deactivate": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @enum {boolean} */
              success: true;
            };
          };
        };
      };
    };
  };
  "/api/admin/users/activate": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @enum {boolean} */
              success: true;
            };
          };
        };
      };
    };
  };
  "/api/me/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              /** @enum {string} */
              role: "user" | "admin";
              /** Format: email */
              email: string;
              firstName: string;
              lastName: string;
            };
          };
        };
      };
    };
  };
  "/api/tags/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              }[];
          };
        };
      };
    };
  };
  "/api/user/auth/register": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
            firstName: string;
            lastName: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              /** @enum {string} */
              role: "user" | "admin";
              /** Format: email */
              email: string;
              firstName: string;
              lastName: string;
            };
          };
        };
      };
    };
  };
  "/api/user/invite/accept": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            email: string;
            signature: string;
            firstName: string;
            lastName: string;
            expireAt: number;
            password: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/user/post/": {
    get: {
      parameters: {
        query?: {
          limit?: number;
          offset?: number;
          page?: number;
          searchQuery?: string;
          sortBy?: "title" | "createdAt" | "commentsCount";
          sortDirection?: "asc" | "desc";
          minCommentsCount?: number;
          tags?: {
              /** Format: uuid */
              id?: string;
              name: string;
            }[];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              meta: {
                total: number;
                limit: number;
                offset: number;
                page: number;
                totalPages: number;
              };
              posts: {
                  id: string;
                  title: string;
                  description: string;
                  authorId: string;
                  author: {
                    id: string;
                    /** Format: email */
                    email: string;
                    firstName: string;
                    lastName: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  };
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: date-time */
                  createdAt: string;
                  commentsCount?: number;
                  tags: {
                      /** Format: uuid */
                      id: string;
                      name: string;
                    }[];
                }[];
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description: string;
            /** @default [] */
            tags?: {
                /** Format: uuid */
                id?: string;
                name: string;
              }[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              title: string;
              description: string;
              authorId: string;
              author: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              comments?: {
                  id: string;
                  postId: string;
                  authorId: string;
                  author: {
                    id: string;
                    /** Format: email */
                    email: string;
                    firstName: string;
                    lastName: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  };
                  text: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
              tags: {
                  /** Format: uuid */
                  id: string;
                  name: string;
                }[];
            };
          };
        };
      };
    };
  };
  "/api/user/post/{postId}/": {
    get: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              title: string;
              description: string;
              authorId: string;
              author: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              comments?: {
                  id: string;
                  postId: string;
                  authorId: string;
                  author: {
                    id: string;
                    /** Format: email */
                    email: string;
                    firstName: string;
                    lastName: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  };
                  text: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
              tags: {
                  /** Format: uuid */
                  id: string;
                  name: string;
                }[];
            };
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            title?: string;
            description?: string;
            /** @default [] */
            tags?: {
                /** Format: uuid */
                id?: string;
                name: string;
              }[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              title: string;
              description: string;
              authorId: string;
              author: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              comments?: {
                  id: string;
                  postId: string;
                  authorId: string;
                  author: {
                    id: string;
                    /** Format: email */
                    email: string;
                    firstName: string;
                    lastName: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  };
                  text: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
              tags: {
                  /** Format: uuid */
                  id: string;
                  name: string;
                }[];
            };
          };
        };
      };
    };
  };
  "/api/user/post/{postId}/comment/": {
    get: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              comments: {
                  id: string;
                  postId: string;
                  authorId: string;
                  author: {
                    id: string;
                    /** Format: email */
                    email: string;
                    firstName: string;
                    lastName: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                  };
                  text: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
            };
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            text: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              postId: string;
              authorId: string;
              author: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
              text: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
  "/api/user/post/{postId}/comment/{commentId}/": {
    patch: {
      parameters: {
        path: {
          postId: string;
          commentId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            text: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              postId: string;
              authorId: string;
              author: {
                id: string;
                /** Format: email */
                email: string;
                firstName: string;
                lastName: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
              text: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description - GENERAL_ERROR -> 1000
     * - EMAIL_USED -> 1001
     * - USER_DISABLED -> 1002
     * @enum {integer}
     */
    ErrorCodes: 1000 | 1001 | 1002;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
